### ISSUE TITLE
Persistent Drawer's transition animation is "detached"

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#201]
### Describe the bug

Drawer's transition animation seems detached from it's layout; it is likely that we used two different css transition style.

### What is the expected behavior?

Drawer's expand/collapse should match perfectly

### What are the steps to reproduce?
1. Spin up the react showcase demo
2. Collapse / expand the drawer by either hover on drawer items or by clicking on the menu icon

### Screenshots or links to minimum reproduction example

Video set to x0.5 speed to illustrate the problem

![drawer-transition](https://user-images.githubusercontent.com/8997218/95618515-309ee500-0a3b-11eb-9631-7445f57a7778.gif)

### Environment

MacOS Chrome

**Comment by joebochill** [comment]
> The transitions are the same, but I suspect there is a race condition when the variables get set to trigger them (drawer gets open/closed state set right away through the prop change, but the DrawerLayout has to wait until the Context is updated). We might need to explore moving some of the drawer logic into the context provider so that these get triggered at the exact same time.

**Comment by joebochill** [comment]
I did a quick and dirty POC to test this out and moving the logic into the DrawerLayout did not have any noticeable effect. The Drawer seems to lead in both animations (opening and closing) regardless. It's less noticeable during the open because the toolbar sits slightly on top of it, but when closing, the drawer leading causes the gap to open.

Very peculiar.

It seems to be more pronounced when there are more items in the drawer. If I render a drawer with no DrawerBody content at all, I can't make the gap appear.

**Comment by emclaug2** [comment]
I also look at this issue; not sure what exactly is going on here.  One thing to point out is that our angular counterpart does not have this issue but uses margins instead of padding to adjust the content.

**Comment by joebochill** [comment]
You can see a very simple React example also does not have the same issue. I’m fairly certain it’s related to the separation of the animations (one happens in the drawer layout and the other in the drawer) and trying to sync them up exactly is tricky.
